/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import Frontend.jconnection.Connector;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Properties;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author SWL
 */
public class ProfileManagement extends javax.swing.JFrame {
Connection con=null; 
PreparedStatement pst=null;
ResultSet rs=null;
String filename=null;
byte[] person_image=null;

    /**
     * Creates new form Login
     */
    
    public ProfileManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jFileChooser1 = new javax.swing.JFileChooser();
        popupMenu1 = new java.awt.PopupMenu();
        popupMenu2 = new java.awt.PopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lastName = new javax.swing.JTextField();
        Phone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Kebele = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        Zone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        Wereda = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Address = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jl_image = new javax.swing.JLabel();
        btn_image = new javax.swing.JButton();
        Electricty = new javax.swing.JRadioButton();
        Customer = new javax.swing.JRadioButton();
        Tele = new javax.swing.JRadioButton();
        Water = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        popupMenu1.setLabel("popupMenu1");

        popupMenu2.setLabel("popupMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 194, 151));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 750));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Manage Your Profile");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Kebele");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 380, -1, -1));

        lastName.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lastName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 153)));
        lastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameActionPerformed(evt);
            }
        });
        jPanel1.add(lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, 230, 30));

        Phone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 153)));
        jPanel1.add(Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 510, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Which Service You Need?");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 520, -1, 20));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Last Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, -1, 20));

        Kebele.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 153)));
        jPanel1.add(Kebele, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 400, 240, 30));

        Email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 153)));
        jPanel1.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 510, 30));

        Zone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 153)));
        jPanel1.add(Zone, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 510, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Email");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, -1, 20));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Zone");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, -1, 20));

        firstName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 153)));
        jPanel1.add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 240, 30));

        Wereda.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 153)));
        jPanel1.add(Wereda, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 240, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("First Name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Kifle Ketema/Wereda");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, -1, 20));

        Address.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 153)));
        jPanel1.add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 510, 30));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Address");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, -1, 20));

        jButton1.setBackground(new java.awt.Color(255, 112, 8));
        jButton1.setText("Save");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 610, 160, 40));

        jButton2.setText("Cancel");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 610, 160, 40));

        jl_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frontend/images.png"))); // NOI18N
        jPanel1.add(jl_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, 130, 120));

        btn_image.setText("Browse");
        btn_image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imageActionPerformed(evt);
            }
        });
        jPanel1.add(btn_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 150, 120, 30));

        Electricty.setText("Electricity Service");
        jPanel1.add(Electricty, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 550, -1, -1));

        Customer.setText("Customer");
        jPanel1.add(Customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 550, -1, -1));

        Tele.setText("Telecom");
        jPanel1.add(Tele, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 550, -1, -1));

        Water.setText("Water Service");
        jPanel1.add(Water, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 550, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Phone Number");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, -1, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imageActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
       chooser.showOpenDialog(null);
            File file=chooser.getSelectedFile();
            jl_image.setIcon(new ImageIcon(file.toString()));
            filename =file.getAbsolutePath();
            ImageIcon imageicon =new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(jl_image.getWidth(), jl_image.getHeight(), Image.SCALE_SMOOTH));
            jl_image.setIcon(imageicon);
            try{
              File image=new File(filename);
              FileInputStream fis = new FileInputStream(image);
              ByteArrayOutputStream bos = new ByteArrayOutputStream();
              byte[] buf=new byte[1024];
              for(int readNum;(readNum=fis.read(buf))!=-1;){
                 bos.write(buf,0,readNum);
              }
             person_image=bos.toByteArray();
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null,ex);
            }
        
    }//GEN-LAST:event_btn_imageActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try{
            
        String query ="INSERT INTO customers (firstname,lastname,email,address,zone,woreda,kebele,phone,service,picture) VALUES(?,?,?,?,?,?,?,?,?,?)";
        try{
        PreparedStatement s=(PreparedStatement) Connector.connect(query);
      
         s.setString(1,firstName.getText());
         s.setString(2,lastName.getText());
         s.setString(3,Email.getText());
         s.setString(4,Address.getText());
         s.setString(5,Zone.getText());
         s.setString(6,Wereda.getText());
         s.setString(7,Kebele.getText());
         s.setString(8,Phone.getText());
          String service ="";
          if(Customer.isSelected()){
              service+=Customer.getText()+" ";
          }
          if(Electricty.isSelected()){
              service+=Electricty.getText()+" ";
          }
          if(Water.isSelected()){
              service+=Water.getText()+" ";
          }
          if(Tele.isSelected()){
              service+=Tele.getText()+" ";
          }
          s.setString(9,service);
          s.setBytes(10,person_image);
          Connector.updateData(s);
            }catch(Exception e){
            System.out.println(e.getMessage());
        }
        JOptionPane.showMessageDialog(this,  "Your profie  modified successfully ");
      
        Custumer_page cust =new Custumer_page();
        cust.setVisible(true);
        this.setVisible(false);
       }catch(Exception ex){
           JOptionPane.showMessageDialog(this,ex.getMessage());
       }
    }//GEN-LAST:event_jButton1ActionPerformed

      public String getFirstName(){
             return firstName.getText();
        }
      public String getEmail(){
          return Email.getText();
      }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfileManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfileManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfileManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfileManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfileManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JRadioButton Customer;
    private javax.swing.JRadioButton Electricty;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Kebele;
    private javax.swing.JTextField Phone;
    private javax.swing.JRadioButton Tele;
    private javax.swing.JRadioButton Water;
    private javax.swing.JTextField Wereda;
    private javax.swing.JTextField Zone;
    private javax.swing.JButton btn_image;
    private javax.swing.JTextField firstName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jl_image;
    private javax.swing.JTextField lastName;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.PopupMenu popupMenu2;
    // End of variables declaration//GEN-END:variables
}
